ENTITY_CODES = %W(R RS RSAD RSADFA RSADHD RSADIT RSADLO RSADMO RSADPM RSADPP RSADWH RSIG RSSA RSSAAD RSSABD RSSACA RSSACH RSSADS
RSSAHV RSSAIT RSSAMA RSSAMF RSSAMK RSSAMP RSSANB RSSAOC RSSAOS RSSAOT RSSAPT RSSATS RSSAUB RSSV RSSVAD RSSVCC RSSVHV RSSVIS RSSVIT
RSSVMF RSSVMP RSSVOS RSSVOT RSSVPP RSSVPT)
